// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhqcbuzqeszfogphklrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJocWNidXpxZXN6Zm9ncGhrbHJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNjgwNjQsImV4cCI6MjA2MTk0NDA2NH0.oT-RpreFCmo7TaLzkSBNx61rgZwZPr_ihx6dhjmqdd4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);